<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cm_ajax"
 *
 * Auto generated by Extension Builder 2014-04-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Fluid Ajax ViewHelpers',
	'description' => 'Fluid ViewHelpers for an easy usage of ajax links and forms in your Extbase Extension',
	'category' => 'plugin',
	'author' => 'Jannes Dinse, Sebastian Tobies, Leon Rönnpagel',
	'author_email' => 'jdinse@codemaschine.de, stobies@codemaschine.de, leworoe@codemaschine.de',
	'author_company' => 'CODE MASCHINE GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.8.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '9.0.0-9.5.99',
			'fluid' => '9.0.0-9.5.99',
			'typo3' => '9.0.0-9.5.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
